### ISSUE TITLE
Encoding bugs

### ISSUE THREAD

**Issue by ko2in** [mockoon/mockoon#847] opened 2022-10-31 06:40 UTC
After upgraded to the newest version (1.21.1), the UI doesn't display the fonts properly when opening the dialog window.

![Mockoon](https://user-images.githubusercontent.com/930315/198946263-4f86ce63-baf1-4c99-872b-fab6060f5dff.png)

Only the settings dialog shows the text properly.

![Mockoon-Settings](https://user-images.githubusercontent.com/930315/198946659-e617f43b-b8d6-4bba-86ea-019d117b8aca.png)

**To Reproduce**

* Start mockoon
* Click the button to create the new environment or open the environment
* The dialog opens and seeing the square fonts

**Mockoon version:**

1.21.1

**OS / OS version:**

Ubuntu 20.04LTS

**Comment by ko2in** [comment] 2022-10-31 06:49
It looks like the bugs only happens with snap package. Uninstalled from snap and installed from .deb package and do not have this bug.

**Comment by 255kb** [comment] 2022-12-01 14:54
Apparently, this is an ongoing bug with Snaps. But it seems to affect only some apps and some users. (also I cannot reproduce it on Ubuntu). 

There are some workaround [there](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/60).
Maybe you could try one of them: 
```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```
I am not sure there is a way we can fix that on our side. I will close it for now.

**Closed by 255kb** 2022-12-01 14:54 UTC
Labels: bug, wontfix
