### ISSUE TITLE
Reusable Responses / Rules

### ISSUE THREAD

**Issue by Hrabal** [mockoon/mockoon#939] opened 2023-02-02 15:48 UTC
It would be useful to have a per-environment container of responses to re-use in multiple routes.

USE-CASE:
401 response returned by every endpoint of a service if no auth header is provided

ideal Mockoon config:
- configure a single 401 response with the specific rule in the "Common Responses" 
- add a response in each route with a reference to the common one

Same thing would be useful for Rules:
USE-CASE:
basic params validation shared across several responses, but each response adds specific validation

ideal Mockoon config:
- configure a single param rule (e.g: "page" should not be empty in queryString)
- add a rule in some responses of type "Common" containing the reference of the common one, the common rule is executed when needed 

Ideally this "common rules" implementation would also have the benefit to add some sort of "nested rules":
- common rule 1: "page" in body AND "page_size" in body
- common rule 2: "offset" in body AND "limit" in body
- rule in the endpoint: common rule 1 OR common rule 2

**Comment by 255kb** [comment] 2023-09-22 15:08
I will close this issue as a duplicate of #221 and continue the discussion there.

**Closed by 255kb** 2023-09-22 15:08 UTC
Labels: duplicate, feature
