### ISSUE TITLE
Console mode

### ISSUE THREAD

**Issue by neonomaly** [mockoon/mockoon#274] opened 2020-03-21 21:49 UTC
Hi!

It would be awesome if it would be possible to start mockoon in console-mode with argument to json file with settings. Like jmeter. May be it is possible now and I missed it? Thank!

**Comment by 255kb** [comment] 2020-03-22 08:24
Hi, this is a duplicate of #62 
I let you react there :)

**Closed by 255kb** 2020-03-22 08:24 UTC
