### ISSUE TITLE
Configure default response to serve by proxy url for specific route if route matched but rules does not matched

### ISSUE THREAD

**Issue by samiransaha** [mockoon/mockoon#414] opened 2021-02-05 15:17 UTC
**Is your feature request related to a problem? Please describe.**
For a mock server, it would be good to have a configuraion where the default response can be configured to if no rules get matched redirect to a proxy server instead of a static mocked response.

**Describe the solution you'd like**
Instead of the static default mocked response, it would be good to have a default response coming from proxy URL response per route basis. So we can have a configuration option where we can change the behavior of no rule matched but route matched. It would be great if we have a proxy URL per route basis, then as a mock server, mockoon can mock multiple dependency services in Integration Test scenarios.

**Describe alternatives you've considered**
It would be a good feature to have in a mock server.

**Additional context**

**Comment by 255kb** [comment] 2021-05-14 14:03
Closing as a duplicate of #363

**Closed by 255kb** 2021-05-14 14:03 UTC
Labels: duplicate, feature
