### ISSUE TITLE
Fail to import environment JSON file

### ISSUE THREAD

**Issue by LukaszGrela** [mockoon/mockoon#222] opened 2019-12-09 09:25 UTC
**Describe the bug**
After recent app update I can't import my environment JSON file, I receive:

![image](https://user-images.githubusercontent.com/7643591/70423483-7a0e5480-1a65-11ea-80c1-bbe861bd0784.png)

an incompatibility issue!

**To Reproduce**
Try to load JSON file saved with previous version of the app

**Expected behavior**
Be able to load that file (all differences resolved by the app on import).

Bare minimum - before uploading notify about breaking changes or give ability to convert from old file to new.

**Mockoon version:**
1.6.0

**OS / OS version:**
Windows 10

**Comment by LukaszGrela** [comment] 2019-12-09 09:26
https://github.com/mockoon/mockoon/releases/tag/v1.6.0 doesnt contain information about breaking changes

**Comment by 255kb** [comment] 2019-12-09 11:37
hi, 
unfortunately, import/export has never been design to work across different versions. It was done a long time ago, and I didn't thought this through...
I will publish a release in the coming days (work is nearly finished) with #212 which will solve this problem. 
Exported files will be compatible with more recent versions and automatically migrated. And older version will be supported too.

Closing as a duplicate of #212

**Closed by 255kb** 2019-12-09 11:37 UTC
