### ISSUE TITLE
Easier method to mock based on query string

### ISSUE THREAD

**Issue by omanizer** [mockoon/mockoon#132] opened 2019-06-03 21:05 UTC
**Is your feature request related to a problem? Please describe.**
Currently it's getting too involved to mock an endpoint and then use a templating switch statement based on a query string variable.  I find myself creating 1 endpoint for /api/widgets and then doing:
{{#switch (queryParam 'page')}}
  {{#case '1'}}
   // response for first page of results
  {{/case}}
  {{#case '2'}}
   // response for second page of results
  {{/case}}
  {{#case '3'}}
   // response for third page of results
  {{/case}}
  etc
{{/switch}}

**Describe the solution you'd like**
I'd like to be able to create all of these as individual routes and include the query string in the route definition.  So something like this:
GET /api/widget?page=1
GET /api/widget?page=2
GET /api/widget?page=3
GET /api/widget <--- This would be the default catch-all

**Describe alternatives you've considered**
None

**Additional context**
I realize express js doesn't allow for targeting route definitions based on query strings, but it would be straightforward to group all routes by their path without the query string and then compare against the query string in the route handler method.

Would this be something that would be considered to be merged?  I think it could be a great way to keep API mocks cleaner as well as make it easier to add a button to the endpoint log that would allow for easily creating a mock based on that endpoint log and what the proxy returned.

**Comment by HeathNaylor** [comment] 2019-08-02 20:08
I support this proposal fully, I may try to implement this myself.

**Comment by 255kb** [comment] 2019-08-02 20:23
I think this will be handled by #75 where we will have multiple responses per route. I am currently working on it and it's nearly finished.
Basically you will be able to add multiple responses for each route declaration, a 200, a 404 etc, and trigger them depending on rules like query param "Foo" equals 1, or body content "user.1.name" equals "Bob".

I think this would solve this issue also.
If you confirm I will close this ticket as a duplicate of #75.

**Comment by HeathNaylor** [comment] 2019-08-05 17:08
Yup, this looks to be a duplicate of #75 .

**Comment by 255kb** [comment] 2019-08-05 19:51
thanks, so I close this in favor of #75

**Closed by 255kb** 2019-08-05 19:51 UTC
