### ISSUE TITLE
CORS response override is not working as expected

### ISSUE THREAD

**Issue by chrischain** [mockoon/mockoon#126] opened 2019-05-06 16:57 UTC
**Describe the bug**
I have attempted to use the CORS Headers feature in the Environment Settings to add headers required by my application, but they are not getting sent by Mockoon.

**To Reproduce**
I am using the single environment "holidays" I have created in Mockoon 1.3.0 on Windows 7 Pro.

I clicked the gear to go into the environment settings, verified the CORS enable box is checked, then went to the Access-Control-Allow-Headers entry in the Environment Headers section below the CORS section.  I appended the three headers my application is looking for: applicationid, login, sessionid to the comma-delimited list.  I then stopped and restarted the server (it did not prompt me to restart).

After restarting the Mockoon server, I sent a request using Chrome Developer Tools.  I get an access blocked/CORS policy error in the console.  When I inspect the response in the Network tab, I see that the three headers I added to the list are not included in the response, only the original ones that were defined are included (Content-Type, Origin, Accept, Authorization, Content-Length, X-Requested-With).

I also tried adding the headers to individual requests, to see if they would append, but they did not.  In addition, I tried wiping out the existing entries listed above, and replacing the list with just my entries, and I still got the original items.

**Expected behavior**
I expect that the three headers I added would be included in the response, and that the preflight request would not be blocked due to CORS policy missing fields.

**Screenshots**
![MockoonSettings](https://user-images.githubusercontent.com/1153561/57241057-0a268000-6fe5-11e9-9589-42a93595e523.png)
![DevTools](https://user-images.githubusercontent.com/1153561/57241067-0d217080-6fe5-11e9-9141-24227a8f5f3d.png)
![DevTools_detail](https://user-images.githubusercontent.com/1153561/57241072-0eeb3400-6fe5-11e9-9d0a-0224d912d99f.png)

**Mockoon version:**
1.3.0

**OS / OS version:**
Windows 7 Professional

**Comment by chrischain** [comment] 2019-05-06 17:57
With further research, I have noted that when using Postman, the request itself does return the expected headers.  It is only the CORS request that does not return the appended headers as expected:
![Postman](https://user-images.githubusercontent.com/1153561/57244592-9dfc4a00-6fed-11e9-8050-b614b652f221.png)

I was able to get my mock api working with the front end by manually adding an options route and disabling CORS in the Environment Settings:
![Mockoon_route](https://user-images.githubusercontent.com/1153561/57244651-b9ffeb80-6fed-11e9-80fc-edc1e34dcb5c.png)

**Comment by cherihung** [comment] 2019-05-08 18:57
oh boy, I've been trying to figure out what my requests aren't working with the environment headers set. Thanks for posting the solution.

**Comment by 255kb** [comment] 2019-05-08 20:05
Thank for the bug report. It is a duplicate of #85 and has already been correct for the next release (coming really soon, in testing phase). 
I am closing this in favor of #85

**Closed by 255kb** 2019-05-08 20:05 UTC
Labels: duplicate

**Comment by chrischain** [comment] 2019-05-08 23:25
cool, thanks... and sorry I didn't catch that it was a duplicate.

**Comment by 255kb** [comment] 2019-05-09 13:43
@chrischain no problem, I also investigated this bug for hours before finding that I solved it for the next version 😄

**Comment by chrischain** [comment] 2019-05-09 14:25
Lol, I hate when that happens!  But thank you, and an extra thank you for a truly great app!

I've been sharing it with all my peers at work, everyone loves it.  The interface is exceptional... and the effort you've put in shows.  Great job!

Chris

**Comment by 255kb** [comment] 2019-05-09 14:33
Thank you for the kind words :) 
A lot is still planned for this app (but development is quite slow as it is only a side project). 
Would you mind sharing a little bit more how you use the app in your team and what feature you miss the most? 
If you agree, you can contact me by direct message on the [spectrum community](https://spectrum.chat/mockoon) or by email hi@mockoon.com. 
It would mean a lot to me :)
