### ISSUE TITLE
Body is cleared when undo (press ctrl+z) immediately after moving from another tab

### ISSUE THREAD

**Issue by taka-shin** [mockoon/mockoon#802] opened 2022-08-23 07:30 UTC
I found what seems to be a bug.
I would appreciate it if you could confirm this report.

**Describe the bug**
Body is cleared in the following cases.

- Undo immediately after moving to Status & Body tab from another tab (Hearders, Rules or Settings)
- Undo immediately after moving to Routes tab from another tab (Headers, Logs, Proxy or Settings)

As a side note, after undoing as above, redo (press ctrl+y) is possible before moving to another (tab, route or environment), but it becomes impossible after moving.

May be related: #309

**To Reproduce**
1. Select a route
2. Edit body (optional if body already exists)
3. Click Headers, Rules or Settings tab
4. Click Status & Body tab
5. Click Body editor and undo (press ctrl+z) -> Body is cleared

**Expected behavior**
Do nothing when undo immediately after moving from another tab.
(Or, keep history for each route.)

**Mockoon version:**
1.20.0

**OS / OS version:**
Windows 10

**Comment by 255kb** [comment] 2024-04-30 08:48
This was apparently fixed by some other change and I cannot reproduce it anymore.

**Closed by 255kb** 2024-04-30 08:48 UTC
Labels: bug
