### ISSUE TITLE
Adding request examples to response

### ISSUE THREAD

**Issue by sayjeyhi** [mockoon/mockoon#354] opened 2020-10-22 20:41 UTC
Hi there,
If we export the environment to open API we need to have examples to the request too. Because there could be a need in which someone works with a team and that team uses postman collections. As we know we could convert open API v3 to postman collections or other formats, and in postman, we could have an example with request and response.
if there was a section in adding routes to set an example request. it could be so useful, at least for me.

Thanks for this great job.

**Comment by 255kb** [comment] 2021-03-05 09:04
Duplicate of #352

**Closed by 255kb** 2021-03-05 09:04 UTC
Labels: duplicate
