### ISSUE TITLE
Allow changing datastore file location

### ISSUE THREAD

**Issue by ams-olx** [mockoon/mockoon#420] opened 2021-02-28 11:48 UTC
I would love to have the option to select where the datastore can be saved as this will allow us to sync the datastore file to any cloud like Google Drive or Dropbox.

Thank you very much...

**Comment by 255kb** [comment] 2021-03-03 10:02
this is on the [roadmap](https://github.com/orgs/mockoon/projects/2) and a duplicate of #16 
But it would indeed be very useful :)

**Closed by 255kb** 2021-03-03 10:02 UTC
Labels: duplicate
