### ISSUE TITLE
add the possibility to have the enviroment proxy as default

### ISSUE THREAD

**Issue by volkerrichert** [mockoon/mockoon#427] opened 2021-03-05 10:40 UTC
I would be very useful to have the proxy to be default if none of the rules in all route matches. At the moment the first one will wacth event if the rules of the first one are not fullfilled

**Comment by volkerrichert** [comment] 2021-03-05 10:47
This could be usefull to have an normal "backend" but add some special cases to it. e.g. simulate timeouts oder other stuff

**Comment by 255kb** [comment] 2021-03-05 11:00
This is a duplicate of #414

**Closed by 255kb** 2021-03-05 11:00 UTC
