### ISSUE TITLE
Add the ability to add our own faker helpers

### ISSUE THREAD

**Issue by DaveMBush** [mockoon/mockoon#1111] opened 2023-08-20 12:46 UTC
I believe Mockoon would be significantly more powerful if we could at least add additional faker.js helpers, of our own creation, to an environment.

At minimum, this would require the ability to add/edit javascript in another panel.  Multiple "file" support would also be useful.

**Comment by 255kb** [comment] 2023-08-20 13:15
Closing as a duplicate of #445

**Closed by 255kb** 2023-08-20 13:15 UTC
Labels: duplicate
