### ISSUE TITLE
Environment file watcher triggered every 30 seconds when file stored on network drive

### ISSUE THREAD

**Issue by Otiel** [mockoon/mockoon#725] opened 2022-06-02 14:01 UTC
**Describe the bug**

I have set "Environment file watcher" to "Prompt". Every 30 seconds, Mockoon detects a change and prompts me to reload my environment, even though no change has been made to the file (confirmed by git).

This bug occurs when the environment file is opened from a network location (network path or mapped network drive), but not when I store the file on my local disk.

I didn't test it with v1.18, I don't know if this is a regression or not.

**To Reproduce**

* Copy the "Demo users API" environment to a network drive.
* Open the environment.
* Wait 30 seconds.

**Mockoon version:**

1.19.0

**OS / OS version:**

Windows 10

**Comment by 255kb** [comment] 2022-06-02 18:48
Thanks for reporting. It's not a regression as it is a new feature in 1.19.0. 

I need to investigate. But after looking at chokidar's issues (the package used for the file watching) it seems that it's usually the opposite with network drives. They are not well monitored and need some polling (which I didn't enable). So, it's rather strange 🤔

**Comment by 255kb** [comment] 2022-06-24 07:35
I investigated a bit and tested various configuration but couldn't reproduce the behavior you are describing. 
I will close it for now, but feel free to reopen if you have more detailed information and/or steps to reproduce the bug.

**Closed by 255kb** 2022-06-24 07:35 UTC
Labels: bug, need investigation
