### ISSUE TITLE
File binary content is served as string

### ISSUE THREAD

**Issue by mikedevel** [mockoon/mockoon#324] opened 2020-07-31 09:34 UTC
Hi everyone, I'm trying to deliver an image through a mockoon endpoint.
I created the route and selected the image, but when I run the route the image is not displayed.
Up to a month ago this route worked perfectly.
Some idea?
Thank you

For clarity I have tried with different images and different formats (jpg, png, etc.) changing the Content-Type from time to time but no change to the result.
With an .json file the endpoint behavior is correct

**Screenshots**
![image](https://user-images.githubusercontent.com/25503927/89021853-78114280-d321-11ea-8c08-9047707b0371.png)

![image](https://user-images.githubusercontent.com/25503927/89021947-94ad7a80-d321-11ea-81ec-5d752eeda89e.png)

![image](https://user-images.githubusercontent.com/25503927/89022048-b1e24900-d321-11ea-8bb5-49f381d34c89.png)

**Mockoon version:**
Latest

**OS / OS version:**
Ubuntu 18.04

**Comment by 255kb** [comment] 2020-07-31 21:33
Hi @mikedevel, thank you for reporting this bug. After investigating, it seems that binary files serving is broken since 1.9.0
The fix is quite simple. This will be done for the next version (no ETA yet).

**Comment by maillouxc** [comment] 2020-08-17 20:11
@255kb You said the fix is quite simple. Can you share the details? We need to to implement this in a local fork.

**Comment by 255kb** [comment] 2020-08-17 22:35
@maillouxc This has been fixed on this branch: https://github.com/mockoon/mockoon/tree/fix/binary-files
Let me know if something still doesn't work.

**Comment by feraguiba** [comment] 2020-08-18 10:55
This is a stopper for us too. In our case, the problem is with PDFs. Please, release the bugfix as soon as possible.

**Comment by maillouxc** [comment] 2020-08-18 19:35
@255kb I appreciate the timely response, you saved the day. However, I have another problem. I'm trying to compile and run that branch, when I run `npm run serve` I get the error: 

[0] ERROR in ../node_modules/@types/express-serve-static-core/index.d.ts:31:10 - error TS2305: Module '"C:/Code/CallMiner.Integrations/Mockoon/node_modules/@types/qs"' has no exported member 'ParsedQs'.
[0]
[0] 31 import { ParsedQs } from "qs";

**Comment by maillouxc** [comment] 2020-08-18 19:39
Nevermind, I cleaned and built again and it worked. Sorry!

**Comment by 255kb** [comment] 2020-08-18 19:40
@maillouxc This is strange I never encountered this error and cannot reproduce. Stupid question, did you run `npm install` recently?  Which version of node are you using?

Branch will be soon merged on master.
I heard you, I will shorten the delay before the next release :)

**Comment by maillouxc** [comment] 2020-08-18 19:44
Thanks for the responsiveness and timely support man. Once I get my project figured out and the feature I need implemented, I'll try to buy you a coffee.

**Comment by 255kb** [comment] 2020-08-18 19:48
@maillouxc You're welcome 😄 
That would be rad! Buts seeing people using this app and enjoying it is already a tremendous reward. 
Also: spread the word ❤️

**Closed** 2020-08-18 19:52 UTC
Labels: bug
