### ISSUE TITLE
unable to add XML/Soap based rules 

### ISSUE THREAD

**Issue by vyomanaut** [mockoon/mockoon#282] opened 2020-04-01 09:53 UTC
I had read somewhere in the official community page that XML rules can be enabled, but I am unable to find how.

**Comment by 255kb** [comment] 2020-04-04 08:19
I think this is a duplicate of #208 where someone proposed a workaround to support XML. Depending on the interest, it could be implemented soon

**Closed by 255kb** 2020-04-04 08:19 UTC
