### ISSUE TITLE
export OpenAPI v3 json file has empty body instead of the mock data

### ISSUE THREAD

**Issue by qiulang** [mockoon/mockoon#437] opened 2021-03-09 08:53 UTC
**Describe the bug**

export OpenAPI v3 json file has empty body instead of the mock data

**To Reproduce**
I use mock sample to reproduce  this problem https://github.com/mockoon/mock-samples/blob/main/samples/open-weather.json.

When export to OpenAPI json this is the result.

```
{
  "openapi": "3.0.0",
  "info": { "title": "Open Weather API", "version": "1.0.0" },
  "servers": [{ "url": "http://localhost:3000/data/2.5" }],
  "paths": {
    "/weather": {
      "get": {
        "description": "Access current weather data for any location on Earth",
        "responses": {
          "200": {
            "description": "",
            "content": { "application/json": {} },
            "headers": { "": { "schema": { "type": "string" }, "example": "" } }
          }
        }
      }
    },
    "/forecast": {
      "get": {
        "description": "Get the hourly weather forecast for 4 days ahead",
        "responses": {
          "200": {
            "description": "",
            "content": { "application/json": {} },
            "headers": { "": { "schema": { "type": "string" }, "example": "" } }
          }
        }
      }
    }
  }
}

```

**Mockoon version:**
1.12.0

**OS / OS version:**
MacOS Big Sur

**Comment by 255kb** [comment] 2021-03-09 09:04
This is a duplicate of #352 . Currently, no example schema is created from the response body.

**Closed by 255kb** 2021-03-09 09:04 UTC
