### ISSUE TITLE
Mockoon MacOS App only uses first item from allOf composition

### ISSUE THREAD

**Issue by jhoffman3** [mockoon/mockoon#1409] opened 2024-06-06 11:27 UTC
Tested 8.2.0 for MacOS both x64 and apple silicon, when importing an openapi specification, ignores all but the first item in  allOf response composition. 

Given a specification that uses allOf for a response:

```
openapi: 3.0.3
info:
  title: Example API
  description: This is an example API using allOf to compose a response.
  version: 1.0.0
paths:
  /example:
    get:
      summary: Get an example response
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
components:
  schemas:
    BaseResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the response
        message:
          type: string
          description: Message of the response
    Data:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier
        name:
          type: string
          description: Name of the entity
    ExampleResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/Data'

```
Import to Mockoon, "data" is missing. 

![image](https://github.com/mockoon/mockoon/assets/30374104/e06d932d-86dc-456f-8677-ec48bdd6874c)

Importing at https://editor.swagger.io/ yields

![image](https://github.com/mockoon/mockoon/assets/30374104/83131b73-9dda-493e-b177-747f013105a9)

Importing to Wiremock also gives the expected response.

Reproduced on 
Mockoon 8.2.0 for MacOS 
M1 Sonoma 14.4
x64 x64 Big Sur, 11.7.10

While Mockoon can't support every feature of the openapi specification every api specification my company produces makes heavy use of allOf.

**Comment by 255kb** [comment] 2024-06-06 13:24
I think this is a duplicate of #1390

**Closed by 255kb** 2024-06-06 13:24 UTC
