### ISSUE TITLE
Maximize mockoon application window.

### ISSUE THREAD

**Issue by aaashutosh** [mockoon/mockoon#357] opened 2020-10-29 13:09 UTC
**Is your feature request related to a problem? Please describe.**
It's frustrating when every time I open Mockoon and it takes up like weird amount of window space with no option to maximize or snap it to one side of the screen.

**Solution I'd like**
Ability to maximize the application window (the ability to snap the window to one side of the screen would be appreciated :) ).  

**Alternatives considered**
Manually resize the app to fit the available space.

**Additional context**
![mockoon](https://user-images.githubusercontent.com/51394064/97577683-d5e42200-1a17-11eb-81ba-25fb063c481b.png)

**OS:** Ubuntu 20.04
**DE**: Gnome, XFCE
**Mockoon version**: 1.10.0

**Comment by 255kb** [comment] 2020-10-29 19:54
Hi @hakanohi this should definitely works 😲 I will investigate!

**Comment by 255kb** [comment] 2021-01-14 20:07
@aaashutosh I cannot reproduce the issue on the Ubuntu installs I have 😞 
I am definitely not a Linux power user, but have you tried to run this command? 
`gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"`

**Comment by aaashutosh** [comment] 2021-01-15 03:33
The maximize button is there but it does not seem to work (using the appimage on a Debian system running XFCE 4.16).

**Comment by 255kb** [comment] 2021-01-17 20:08
I just tested on Debian with XFCE (in a VM) and everything was working fine. I may not have tested with the exact same settings though. I will change a bit the options passed to the Electron window. I saw some issues resolved with this, we will see. It will be in the next update.

**Closed** 2021-01-17 20:19 UTC
Labels: bug, need feedback

**Comment by UmeshG-24099** [comment] 2022-12-12 13:30
> @aaashutosh I cannot reproduce the issue on the Ubuntu installs I have disappointed I am definitely not a Linux power user, but have you tried to run this command? `gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"`

Thank you its work
