### ISSUE TITLE
Remove version from export/import environments

### ISSUE THREAD

**Issue by rogeriocsilva** [mockoon/mockoon#215] opened 2019-11-21 10:46 UTC
**Describe the bug**
Just had a colleague doing a fresh install, and when importing my environment it'd get an error saying "data was not compatible with it version"

**Expected behavior**
Just remove the app version when not needed, since it to work, it had to change the file version to the app version

**Screenshots**
![image](https://user-images.githubusercontent.com/10121694/69331070-0e964b80-0c4c-11ea-9dc3-76055ebf6ae8.png)

**Mockoon version:**
"appVersion": "1.5.1" -> "appVersion": "1.6.0",

**OS / OS version:**
Mac OS, Linux Ubuntu 16.04

**Comment by 255kb** [comment] 2019-11-21 20:56
Indeed, you can just change the version, but the import won't play the migrations on the data (code is quite old now). 
It will solve your specific problem without major error because migration between 1.5.1 and 1.6.0 was small. 

But we need to both get rid of the version check and play the migrations during an import. This is already covered by #212 and planned for next release.
So I will close this as a duplicate of #212.

**Closed by 255kb** 2019-11-21 20:56 UTC

**Comment by rogeriocsilva** [comment] 2019-11-22 11:16
I also had a problem with this approach. When importing an environment json from the 1.5.1 version to the 1.6.0, all my requests where getting CORS problems. I tried tweaking the cors settings again, but nothign seem to work, forcing both me and my teammate to install the 1.5.1 version.

**Comment by 255kb** [comment] 2019-11-22 11:36
This is strange. The only difference are migration played or not. And no migration concerned CORS.

**Comment by rogeriocsilva** [comment] 2019-11-25 11:28
Don't know, I could try again and submit a new issue if you want.
