### ISSUE TITLE
Pretty print response body

### ISSUE THREAD

**Issue by piotrtobolski** [mockoon/mockoon#545] opened 2021-08-16 14:05 UTC
**Is your feature request related to a problem? Please describe.**
When I'm using environment logs feature I'm frustrated that I see raw JSON body. I haven't found any way to preview it in formatted (readable) way other than copy it to another program. 

**Describe the solution you'd like**
I would like to see a button next to "Body (raw)" that will let me preview the body in a formatted way. I'm using JSON as (I expect) most others but it could work for other formats as well. I would like it to remember this setting so I don't need to click it again when I change request from the list.

**Describe alternatives you've considered**
I think it could be also sone within the "View full body in editor" but that is cumbersome as it would require second click and a lot of mouse movement to compare responses

I also though about pretty printing being the default and only view here but it wouldn't allow to show the actual response content so it is unacceptable.

**Additional context**
none

**Comment by 255kb** [comment] 2021-08-17 11:47
Closing as a duplicate of #368
Similar ideas are discussed there and we will surely find a solution hat is performant and easy to use

**Closed by 255kb** 2021-08-17 11:47 UTC
